### ISSUE TITLE
This plugin is great.

### ISSUE THREAD

**Issue by a4jp-com** [iamntz/Register-Plus-Redux#1]
This plugin is exactly what I'm looking for. Need any help fixing security bugs?

**Comment by a4jp-com** [comment]
Is anyone still interested in getting updates for this plugin?

**Comment by iamntz** [comment]
Sure.

But keep in mind, i'm not the author, it's just a clone of the official plugin (which i just noticed is gone) :)

**Comment by a4jp-com** [comment]
Oh. How do we get it back in the plugin directory?

**Comment by iamntz** [comment]
I have no idea at this moment :)

Considering bad reviews received [here](https://wordpress.org/support/plugin/register-plus-redux/reviews/?filter=1), I'd say that sometime after my cloning, things went a bit south.

**Comment by a4jp-com** [comment]
If it's worth it I'll try publishing it in the plugin directory again. If it is just here not a lot of people will find it.

**Comment by a4jp-com** [comment]
I see what you mean. The password would need to be fixed and the code would need the obfuscated lines removed. Depending on what it was made with I might be able to remove the obfuscated code. I'll have a look tonight. Are you a programmer as well?

**Comment by iamntz** [comment]
Yeah, I started to improve the overall code, will publish on WP repo after i'm done.

**Comment by a4jp-com** [comment]
I couldn't see the obfuscated lines of code. Are they still in one of the files somewhere?

**Comment by iamntz** [comment]
Well, to be honest, i never saw any obfuscated code; i read on the wp plugins page about this, but i never see it :)

**Comment by a4jp-com** [comment]
Guess that means the other person had loaded a bad plugin or something that was messing up their site.

At least that means there is one less problem to fix here. ^^
