### ISSUE TITLE
Password sanitization

### ISSUE THREAD

**Issue by DigiEggz** [iamntz/Register-Plus-Redux#11]
Within the `rpr_login_filter_random_password()` function in both rpr-login.php and rpr-signup.php, there's the following line of code:

`$password = sanitize_text_field( (string) $_POST['pass1'] );`

This causes an issue because sanitizing user passwords greatly increases password entropy and also causes issues logging in later because the password is stripped of normally accepted characters, such as spaces. I think that the line should just read `$password =  $_POST['pass1']; ` since WordPress sanitizes passwords internally.

**Comment by iamntz** [comment]
Thanks for your issue! However, this repo is a mirror of the old plugin (which isn't available anymore). I'm not its developer :)

**Comment by DigiEggz** [comment]
I thought that you had plans to "improve this one a bit", as the description states? I would be happy to make the changes and push them if you'd like. If you're not interested I can just make a fork.

**Comment by iamntz** [comment]
Yeah, that was the plan, but then the project where I needed this changed, time was very scarce, the code was too tangled, I had no motivation whatsoever to work on it, long story short, I also kind of abandon it 😀 

You're free to fork it.

**Comment by DigiEggz** [comment]
Did you end up going with a different plugin? Thanks for the info btw!

**Comment by iamntz** [comment]
Nope, the project this was needed was abandoned. 

However, I noticed there are a bunch of high-rated plugins on Code Canyon, so if you're in a hurry that might be a better start :)
