### ISSUE TITLE
Improve code readability

### ISSUE THREAD

**Issue by iamntz** [iamntz/Register-Plus-Redux#6]
- [ ] Apply PSR or WP coding style;
- [ ] Remove inline comments:

```
example of inline comments:
public /*.string.*/ function rpr_filter_verification_mail_from_name( /*.string.*/ $from_name ) {
	return esc_html( $this->rpr_get_option( 'verification_message_from_name' ) );
}
```

**Comment by a4jp-com** [comment]
Is there anything I can do here? Is the current code kind of working? I haven't tested it yet.

**Comment by iamntz** [comment]
The current master branch is the original code, so that's working.

Right now I won't need any help, since I refactor a whole bunch of stuff.
